#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import print_function
import argparse
import hashlib
import os
import os.path
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

DEBUG = os.environ.get("JAVAENV_DEBUG") == "true"
JAVAENV_HOME = os.environ.get("JAVAENV_HOME",
                              os.path.expanduser("~/.javaenv/"))
VERSIONS_DIR = os.path.join(JAVAENV_HOME, "versions/")
DEFAULT_VERSION_FILE = os.path.join(JAVAENV_HOME, "version")
OS = sys.platform

VERSIONS = {
    "adoptopenjdk-8u222": {
        "darwin": {
            "url": "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_mac_hotspot_8u222b10.tar.gz",
            "home_dir": "jdk8u222-b10/Contents/Home",
            "sha256": "9605fd00d2960934422437f601c7a9a1c5537309b9199d5bc75f84f20cd29a76"
        },
        "linux": {
            "url": "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz",
            "home_dir": "jdk8u222-b10",
            "sha256": "37356281345b93feb4212e6267109b4409b55b06f107619dde4960e402bafa77"
        },
    },
    "corretto-11.0.4.11.1": {
        "darwin": {
            "url": "https://d3pxv6yz143wms.cloudfront.net/11.0.4.11.1/amazon-corretto-11.0.4.11.1-macosx-x64.tar.gz",
            "home_dir": "amazon-corretto-11.jdk/Contents/Home",
            "md5": "44bb1e1e6368e1b0f994f5e899b0adc9"
        },
        "linux": {
            "url": "https://d3pxv6yz143wms.cloudfront.net/11.0.4.11.1/amazon-corretto-11.0.4.11.1-linux-x64.tar.gz",
            "home_dir": "amazon-corretto-11.0.4.11.1-linux-x64",
            "md5": "4bbcd5e6d721fef56e46b3bfa8631c1c"
        }
    },
    "openjdk-9.0.4": {
        "darwin": {
            "url": "https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-9.0.4_osx-x64_bin.tar.gz",
            "home_dir": "jdk-9.0.4.jdk/Contents/Home",
            "sha256": "66415406716fc42cff36e2d74ae991d46c42b3cf317b0425c7bf67697c616716"
        },
        "linux": {
            "url": "https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-9.0.4_linux-x64_bin.tar.gz",
            "home_dir": "jdk-9.0.4",
            "sha256": "39362fb9bfb341fcc802e55e8ea59f4664ca58fd821ce956d48e1aa4fb3d2dec"
        }
    },
    "openjdk-11.0.1": {
        "darwin": {
            "url": "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz",
            "home_dir": "jdk-11.0.1.jdk/Contents/Home",
            "sha256": "fa07eee08fa0f3de541ee1770de0cdca2ae3876f3bd78c329f27e85c287cd070"
        },
        "linux": {
            "url": "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz",
            "home_dir": "jdk-11.0.1",
            "sha256": "7a6bb980b9c91c478421f865087ad2d69086a0583aeeb9e69204785e8e97dcfd"
        }
    },
    "openjdk-11.0.2": {
        "darwin": {
            "url": "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz",
            "home_dir": "jdk-11.0.2.jdk/Contents/Home",
            "sha256": "f365750d4be6111be8a62feda24e265d97536712bc51783162982b8ad96a70ee"
        },
        "linux": {
            "url": "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz",
            "home_dir": "jdk-11.0.2",
            "sha256": "99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57"
        }
    },
    "openjdk-12": {
        "darwin": {
            "url": "https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_osx-x64_bin.tar.gz",
            "home_dir": "jdk-12.jdk/Contents/Home",
            "sha256": "52164a04db4d3fdfe128cfc7b868bc4dae52d969f03d53ae9d4239fe783e1a3a"
        },
        "linux": {
            "url": "https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_linux-x64_bin.tar.gz",
            "home_dir": "jdk-12",
            "sha256": "b43bc15f4934f6d321170419f2c24451486bc848a2179af5e49d10721438dd56"
        }
    },
    "oracle-12.0.2": {
        "darwin": {
            "url": "https://download.oracle.com/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_osx-x64_bin.tar.gz",
            "home_dir": "jdk-12.0.2.jdk/Contents/Home",
            "sha256": "675a739ab89b28a8db89510f87cb2ec3206ec6662fb4b4996264c16c72cdd2a1"
        },
        "linux": {
            "url": "https://download.oracle.com/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_linux-x64_bin.tar.gz",
            "home_dir": "jdk-12.0.2",
            "sha256": "75998a6ebf477467aa5fb68227a67733f0e77e01f737d4dfbc01e617e59106ed"
        }
    },
} # yapf: disable


def eprint(msg):
    print(msg, file=sys.stderr)


def debug(msg):
    if DEBUG:
        eprint(msg)


def get_version_blob(version):
    return VERSIONS[version][OS]

def make_versions_dir():
    if not os.path.exists(VERSIONS_DIR):
        os.makedirs(VERSIONS_DIR)
        debug("Created versions dir: %s" % VERSIONS_DIR)
    return VERSIONS_DIR


def get_version_dir(version):
    return os.path.join(VERSIONS_DIR, "%s/" % version)


def make_version_dir(version):
    version_dir = get_version_dir(version)
    if not os.path.exists(version_dir):
        os.makedirs(version_dir)
    return version_dir


def get_installed_versions():
    debug("getting installed versions")
    versions = os.listdir(make_versions_dir())
    debug(versions)
    return versions


def get_download_url(version):
    debug("getting download url for " + version)
    return get_version_blob(version)["url"]


def is_version_installed(version):
    version_dir = get_version_dir(version)
    return os.path.exists(version_dir)


def get_java_home(version):
    if is_version_installed(version):
        return os.path.join(make_version_dir(version), get_version_blob(version)["home_dir"])
    else:
        raise Exception("No installed versions of Java matched " + version)


def verify_hash(version, path):
    blob = get_version_blob(version)
    if "sha256" in blob:
        hash = hashlib.sha256()
        expected_hash = blob["sha256"]
    else:
        hash = hashlib.md5()
        expected_hash = blob["md5"]

    with open(path, 'rb') as f:
        while True:
            data = f.read(65536)
            if not data:
                break
            hash.update(data)
    if "{0}".format(hash.hexdigest()) != expected_hash:
        raise Exception("Unexpected hash for downloaded file, aborting")


def download(version):
    url = get_download_url(version)
    debug("downloading %s" % url)
    tmp_file = tempfile.mktemp()
    urllib.request.urlretrieve(
        url, tmp_file,
        lambda b, bs, t: print_progress(b * bs, t, suffix="Download %s" % url))
    print()  # print newline after progress bar
    debug("downloaded")

    debug("verifying hash")
    verify_hash(version, tmp_file)

    version_dir = make_version_dir(version)

    tar = tarfile.open(tmp_file)
    tar.extractall(path=version_dir)
    tar.close()
    debug("extracted")
    debug(version + " available at " + get_java_home(version))


def install(version):
    debug("install " + version)
    installed_versions = get_installed_versions()
    if version in installed_versions:
        debug("Already installed")
    else:
        download(version)


def uninstall(version):
    version_dir = get_version_dir(version)
    if os.path.exists(version_dir):
        debug("Removing %s" % version_dir)
        shutil.rmtree(version_dir)
        debug("Removed %s" % version_dir)
    else:
        eprint("Version not installed")


def list_installed():
    for version in sorted(get_installed_versions()):
        print(version)


def list_remote():
    for version in VERSIONS:
        print(version)


def get_version_from_file(path):
    debug("Getting version from " + path)
    with open(path, 'r') as f:
        version = f.read().strip()
        debug("Read " + version + " from " + path)
        return version


def get_version(argv_version):
    java_version_file = ".javaversion"
    if argv_version:
        debug("Getting version from command line")
        version = argv_version
    elif os.path.exists(java_version_file):
        version = get_version_from_file(java_version_file)
    elif os.path.exists(DEFAULT_VERSION_FILE):
        version = get_version_from_file(DEFAULT_VERSION_FILE)
    else:
        raise Exception(
            "Undefined version, make sure you run this command from a directory with a .javaversion file, or provide a default version in %s" % DEFAULT_VERSION_FILE
        )

    if version[0].isdigit():
        return "openjdk-" + version
    else:
        return version


def print_progress(iteration, total, suffix, bar_length=50):
    str_format = "{0:.1" + "f}"
    percents = str_format.format(100 * (iteration / float(total)))
    filled_length = int(round(bar_length * iteration / float(total)))
    bar = '█' * filled_length + '-' * (bar_length - filled_length)

    sys.stdout.write('\r|%s| %s%s %s' % (bar, percents, '%', suffix)),

    sys.stdout.flush()


def javaenv():
    parser = argparse.ArgumentParser(description='Java version manager')
    subparsers = parser.add_subparsers(dest='cmd')

    install_parser = subparsers.add_parser('install',
                                           help='Install a Java version')
    install_parser.add_argument(
        'version',
        nargs='?',
        default=None,
        help='version to install, default to using .javaversion')

    home_parser = subparsers.add_parser('home', help='Print active JAVA_HOME')
    home_parser.add_argument(
        'version',
        nargs='?',
        default=None,
        help='version to use, default to using .javaversion')

    subparsers.add_parser('list', help='List installed versions')

    uninstall_parser = subparsers.add_parser('uninstall',
                                             help='Uninstall a version')
    uninstall_parser.add_argument('version', help='version to uninstall')

    subparsers.add_parser('list-remote', help='List all installable versions')

    args = parser.parse_args()
    cmd = args.cmd
    if cmd == "install":
        install(get_version(args.version))
    elif cmd == "home":
        print(get_java_home(get_version(args.version)))
    elif cmd == "uninstall":
        uninstall(args.version)
    elif cmd == "list":
        list_installed()
    elif cmd == "list-remote":
        list_remote()
    else:
        parser.print_usage()


if __name__ == "__main__":
    bn = os.path.basename(sys.argv[0])
    try:
        if bn == "javaenv":
            javaenv()
        else:
            cmd = os.path.join(get_java_home(get_version(None)), "bin/", bn)
            args = [cmd] + sys.argv[1:]
            p = subprocess.run(args)
            sys.exit(p.returncode)
    except Exception as e:
        print(e)
        sys.exit(1)
